[project]
name = "python-learning2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Roman Turlai", email = "roman.turlai@trinetix.com" }
]
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
]

[project.scripts]
python-learning2 = "python_learning2:main"

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.3",
]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "SIM", "S"]
